// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: soupe/v1/messages.proto

package pbsoupev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	MsgType_Unknown    MsgType = 0
	MsgType_Ping       MsgType = 1
	MsgType_Hello      MsgType = 2
	MsgType_Welcome    MsgType = 3
	MsgType_Connect    MsgType = 4
	MsgType_Reconnect  MsgType = 5
	MsgType_Disconnect MsgType = 6
	MsgType_Max        MsgType = 7
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "Unknown",
		1: "Ping",
		2: "Hello",
		3: "Welcome",
		4: "Connect",
		5: "Reconnect",
		6: "Disconnect",
		7: "Max",
	}
	MsgType_value = map[string]int32{
		"Unknown":    0,
		"Ping":       1,
		"Hello":      2,
		"Welcome":    3,
		"Connect":    4,
		"Reconnect":  5,
		"Disconnect": 6,
		"Max":        7,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_soupe_v1_messages_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_soupe_v1_messages_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_soupe_v1_messages_proto_rawDescGZIP(), []int{0}
}

type MsgDone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            *bool                  `protobuf:"varint,1,opt,name=ok,proto3,oneof" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgDone) Reset() {
	*x = MsgDone{}
	mi := &file_soupe_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDone) ProtoMessage() {}

func (x *MsgDone) ProtoReflect() protoreflect.Message {
	mi := &file_soupe_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDone.ProtoReflect.Descriptor instead.
func (*MsgDone) Descriptor() ([]byte, []int) {
	return file_soupe_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *MsgDone) GetOk() bool {
	if x != nil && x.Ok != nil {
		return *x.Ok
	}
	return false
}

type MsgError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	What          string                 `protobuf:"bytes,2,opt,name=what,proto3" json:"what,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgError) Reset() {
	*x = MsgError{}
	mi := &file_soupe_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgError) ProtoMessage() {}

func (x *MsgError) ProtoReflect() protoreflect.Message {
	mi := &file_soupe_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgError.ProtoReflect.Descriptor instead.
func (*MsgError) Descriptor() ([]byte, []int) {
	return file_soupe_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *MsgError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MsgError) GetWhat() string {
	if x != nil {
		return x.What
	}
	return ""
}

type MsgHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        []byte                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgHello) Reset() {
	*x = MsgHello{}
	mi := &file_soupe_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgHello) ProtoMessage() {}

func (x *MsgHello) ProtoReflect() protoreflect.Message {
	mi := &file_soupe_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgHello.ProtoReflect.Descriptor instead.
func (*MsgHello) Descriptor() ([]byte, []int) {
	return file_soupe_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *MsgHello) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

type MsgConnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hwid          []byte                 `protobuf:"bytes,1,opt,name=hwid,proto3" json:"hwid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgConnect) Reset() {
	*x = MsgConnect{}
	mi := &file_soupe_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgConnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgConnect) ProtoMessage() {}

func (x *MsgConnect) ProtoReflect() protoreflect.Message {
	mi := &file_soupe_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgConnect.ProtoReflect.Descriptor instead.
func (*MsgConnect) Descriptor() ([]byte, []int) {
	return file_soupe_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *MsgConnect) GetHwid() []byte {
	if x != nil {
		return x.Hwid
	}
	return nil
}

type MsgHello_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        []byte                 `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgHello_Response) Reset() {
	*x = MsgHello_Response{}
	mi := &file_soupe_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgHello_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgHello_Response) ProtoMessage() {}

func (x *MsgHello_Response) ProtoReflect() protoreflect.Message {
	mi := &file_soupe_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgHello_Response.ProtoReflect.Descriptor instead.
func (*MsgHello_Response) Descriptor() ([]byte, []int) {
	return file_soupe_v1_messages_proto_rawDescGZIP(), []int{2, 0}
}

func (x *MsgHello_Response) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

var File_soupe_v1_messages_proto protoreflect.FileDescriptor

const file_soupe_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x17soupe/v1/messages.proto\x12\x12limboware.soupe.v1\"%\n" +
	"\aMsgDone\x12\x13\n" +
	"\x02ok\x18\x01 \x01(\bH\x00R\x02ok\x88\x01\x01B\x05\n" +
	"\x03_ok\"2\n" +
	"\bMsgError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x12\n" +
	"\x04what\x18\x02 \x01(\tR\x04what\"F\n" +
	"\bMsgHello\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\fR\x06pubkey\x1a\"\n" +
	"\bResponse\x12\x16\n" +
	"\x06pubkey\x18\x02 \x01(\fR\x06pubkey\" \n" +
	"\n" +
	"MsgConnect\x12\x12\n" +
	"\x04hwid\x18\x01 \x01(\fR\x04hwid*m\n" +
	"\aMsgType\x12\v\n" +
	"\aUnknown\x10\x00\x12\b\n" +
	"\x04Ping\x10\x01\x12\t\n" +
	"\x05Hello\x10\x02\x12\v\n" +
	"\aWelcome\x10\x03\x12\v\n" +
	"\aConnect\x10\x04\x12\r\n" +
	"\tReconnect\x10\x05\x12\x0e\n" +
	"\n" +
	"Disconnect\x10\x06\x12\a\n" +
	"\x03Max\x10\aB(Z&limboware/pkg/proto/soupe/v1;pbsoupev1b\x06proto3"

var (
	file_soupe_v1_messages_proto_rawDescOnce sync.Once
	file_soupe_v1_messages_proto_rawDescData []byte
)

func file_soupe_v1_messages_proto_rawDescGZIP() []byte {
	file_soupe_v1_messages_proto_rawDescOnce.Do(func() {
		file_soupe_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_soupe_v1_messages_proto_rawDesc), len(file_soupe_v1_messages_proto_rawDesc)))
	})
	return file_soupe_v1_messages_proto_rawDescData
}

var file_soupe_v1_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_soupe_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_soupe_v1_messages_proto_goTypes = []any{
	(MsgType)(0),              // 0: limboware.soupe.v1.MsgType
	(*MsgDone)(nil),           // 1: limboware.soupe.v1.MsgDone
	(*MsgError)(nil),          // 2: limboware.soupe.v1.MsgError
	(*MsgHello)(nil),          // 3: limboware.soupe.v1.MsgHello
	(*MsgConnect)(nil),        // 4: limboware.soupe.v1.MsgConnect
	(*MsgHello_Response)(nil), // 5: limboware.soupe.v1.MsgHello.Response
}
var file_soupe_v1_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_soupe_v1_messages_proto_init() }
func file_soupe_v1_messages_proto_init() {
	if File_soupe_v1_messages_proto != nil {
		return
	}
	file_soupe_v1_messages_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_soupe_v1_messages_proto_rawDesc), len(file_soupe_v1_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_soupe_v1_messages_proto_goTypes,
		DependencyIndexes: file_soupe_v1_messages_proto_depIdxs,
		EnumInfos:         file_soupe_v1_messages_proto_enumTypes,
		MessageInfos:      file_soupe_v1_messages_proto_msgTypes,
	}.Build()
	File_soupe_v1_messages_proto = out.File
	file_soupe_v1_messages_proto_goTypes = nil
	file_soupe_v1_messages_proto_depIdxs = nil
}
